### ISSUE TITLE
Uploaded documents cannot be retrieved

### ISSUE THREAD

**Issue by lid** [bitnami/bitnami-docker-suitecrm#78]
**Description**

Documents are successfully uploaded, but cannot be retrieved; HTTP 500 error thrown.

**Steps to reproduce the issue:**

1. Upload a document to the documents module
2. Try to download it

**Describe the results you received:**

HTTP 500, log shows:
```
suitecrm_1  | 172.18.0.1 - - [27/Mar/2018:06:37:24 +0000] "GET /index.php?entryPoint=download&id=827fecec-daf6-8383-0e84-5ab9e66ffa27&type=Documents HTTP/1.1" 500 -
```
The corresponding errors in error_log:
```
[Tue Mar 27 06:44:29.343423 2018] [:error] [pid 339] [client 10.158.2.93:61512] PHP Warning:  require_once(download.php): failed to open stream: No such file or directory in /bitnami/suitecrm/include/MVC/Controller/SugarController.php on line 1014, referer: https://x.x.x.x/index.php?module=Documents&action=index&parentTab=All
[Tue Mar 27 06:44:29.343456 2018] [:error] [pid 339] [client 10.158.2.93:61512] PHP Fatal error:  require_once(): Failed opening required 'download.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/include/MVC/Controller/SugarController.php on line 1014, referer: https://x.x.x.x/index.php?module=Documents&action=index&parentTab=All
```

**Describe the results you expected:**

The file that was uploaded to the documents module is successfully retrieved.

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:06:22 2018
 OS/Arch:	darwin/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:14:32 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

- Output of `docker info`:

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 6
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: RD4F:SZVH:6BJD:RLGW:QIVX:OCXK:ZAAJ:DR3T:NPWD:M2IP:MJ42:OEBT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 54
 Goroutines: 83
 System Time: 2018-03-27T06:46:47.5221233Z
 EventsListeners: 4
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2n  7 Dec 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @lid I was able to reproduce the issue. See the error obtained on the Apache Error log:

```
PHP Fatal error:  require_once(): Failed opening required 'download.php' (include_path='/bitnami/suitecrm:/bitnami/suitecrm/include/HTMLPurifier/standalone:/bitnami/suitecrm/include/..:.:/opt/bitnami/php/lib/php') in /bitnami/suitecrm/include/MVC/Controller/SugarController.php on line 1014, referer: http://127.0.0.1/index.php?module=Documents&action=index
```

Thanks for reporting it. I created a task to investigate this issue and included it in our backlog.

We will update this thread as soon as we have more news.

**Comment by lid** [comment]
This looks like an include_path issue, similar to #79. 

Being new to Bitnami, I'm curious how components like SuiteCRM are defined and set up - I assume it is through the .nami components, but where is the source repository for those components, since they don't seem to be in this repo?

**Comment by juan131** [comment]
Hi @lid 

As you mentioned the setup is done by the [Nami](https://github.com/bitnami/nami) modules (apache, php, mysql-client & suitecrm ones on this image)
 
Currently the repository which includes the Nami module logic is not public. They are installed under `./root/.nami/components/`where you can find the logic.

**Comment by juanluisbaptiste** [comment]
I'm having this exact behavior when trying to download the import contacts template. I get a blank page when trying to download it and on apache's error log I get the same error than comment  #2. Is there a way to workaround this ?

**Comment by carrodher** [comment]
Hi,
The issue should be solved in the latest version. Using the latest version
```
image: 'bitnami/suitecrm:7'
```
the issue doesn't appear, but for example, using a previous version
```
image: 'bitnami/suitecrm:7.10.3-r0'
```
we can reproduce the issue. Can you try the latest version?

**Comment by juanluisbaptiste** [comment]
If I copy /opt/bitnami/suitecrm/export.php to /bitnami/suitecrm/ the error goes away.

**Comment by juanluisbaptiste** [comment]
For now as a workaround I built a custom image and add the missing file there:

`FROM bitnami/suitecrm:latest
LABEL maintainer "Juan Luis Baptiste <jbaptiste@xxxxxx.com>"

RUN mkdir -p /bitnami/suitecrm && \
    cp /opt/bitnami/suitecrm/export.php /bitnami/suitecrm/
`

**Comment by juanluisbaptiste** [comment]
No, the custom image wasn't necessary, just copy the file to /bitnami and as it is a mounted volume it will persist after container restart.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

I'm unable to reproduce the issue using the latest image. I followed the steps: Sales->Contacts->Import Contacts->Download import file template

Could you please ensure you're using the latest docker image? What do you obtain when running he command below?

```
$ docker images | grep suitecrm
```

**Comment by juanluisbaptiste** [comment]
Hi,

```
bitnami/suitecrm                                               7                   afe3993b028a        6 days ago          424 MB
bitnami/mariadb                                                latest              f4c23cd4f2bb        13 days ago         286 MB
bitnami/suitecrm                                               latest              55357ddd0eb3        13 days ago         424 MB

```

And on the compose file I'm using bitnami/suitecrm:7 as this was the tag thet @carrodher said was working.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

It seems you're using a 6 days old image, please use the latest one. You can update the image running the command:

```
docker pull bitnami/suitecrm:7
```

**Comment by carrodher** [comment]
I was talking about the original issue, the one related to upload documents to the documents module
and try to download it. I checked that this issue was solved in the latest versions.

About the Contacts issue, @juan131 was unable to reproduce it using the latest image.

Sorry for the misunderstanding.

**Comment by juanluisbaptiste** [comment]
@juan131 I tested that time with an image pulled _after_ I so @carrodher  message. Anyways, I just pulled again and I still see the problem, same error about export.php.
```
$ sudo docker images|grep bitnami
bitnami/suitecrm                                               7                   e29a15d45b40        2 hours ago         429 MB
bitnami/suitecrm                                               latest              e29a15d45b40        2 hours ago         429 MB
bitnami/mariadb                                                latest              f4c23cd4f2bb        2 weeks ago         286 MB

```

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

Are you persisting the data on your containers? You might have updated the image but the configuration is persisted using the old code instead of the new one that fixes the issue.

**Comment by juanluisbaptiste** [comment]
@juan131 

Yes, I'm persisting volumes, but I can't delete them as it's a production install. What changes or from where can I download the new config ?

**Comment by juan131** [comment]
There you have it... The configuration file we modified to fix this issue is on the list of persisted files... 

@juanluisbaptiste let's try with this:

* Locate the file **/bitnami/suitecrm/include/MVC/Controller/entry_point_registry.php** on the persisted directory. Then edit it so the block below:

```
$entry_point_registry = array(
...
);
```

Looks like this:

```
$entry_point_registry = array(
    'emailImage' => array('file' => '/opt/bitnami/suitecrm/modules/EmailMan/EmailImage.php', 'auth' => false),
    'download' => array('file' => '/opt/bitnami/suitecrm/download.php', 'auth' => true),
    'export' => array('file' => '/opt/bitnami/suitecrm/export.php', 'auth' => true),
    'export_dataset' => array('file' => '/opt/bitnami/suitecrm/export_dataset.php', 'auth' => true),
    'Changenewpassword' => array('file' => '/opt/bitnami/suitecrm/modules/Users/Changenewpassword.php', 'auth' => false),
    'GeneratePassword' => array('file' => '/opt/bitnami/suitecrm/modules/Users/GeneratePassword.php', 'auth' => false),
    'vCard' => array('file' => '/opt/bitnami/suitecrm/vCard.php', 'auth' => true),
    'pdf' => array('file' => '/opt/bitnami/suitecrm/pdf.php', 'auth' => true),
    'minify' => array('file' => '/opt/bitnami/suitecrm/jssource/minify.php', 'auth' => true),
    'json_server' => array('file' => '/opt/bitnami/suitecrm/json_server.php', 'auth' => true),
    'get_url' => array('file' => '/opt/bitnami/suitecrm/get_url.php', 'auth' => true),
    'HandleAjaxCall' => array('file' => '/opt/bitnami/suitecrm/HandleAjaxCall.php', 'auth' => true),
    'TreeData' => array('file' => '/opt/bitnami/suitecrm/TreeData.php', 'auth' => true),
    'image' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/image.php', 'auth' => false),
    'campaign_trackerv2' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/Tracker.php', 'auth' => false),
    'WebToLeadCapture' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/WebToLeadCapture.php', 'auth' => false),
    'WebToPersonCapture' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/WebToPersonCapture.php', 'auth' => false),
    'removeme' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/RemoveMe.php', 'auth' => false),
    'ConfirmOptIn' => array('file' => '/opt/bitnami/suitecrm/include/entryPointConfirmOptInConnector.php', 'auth' => false),
    'acceptDecline' => array('file' => '/opt/bitnami/suitecrm/modules/Contacts/AcceptDecline.php', 'auth' => false),
    'leadCapture' => array('file' => '/opt/bitnami/suitecrm/modules/Leads/Capture.php', 'auth' => false),
    'process_queue' => array('file' => '/opt/bitnami/suitecrm/process_queue.php', 'auth' => true),
    'zipatcher' => array('file' => '/opt/bitnami/suitecrm/zipatcher.php', 'auth' => true),
    'mm_get_doc' => array('file' => '/opt/bitnami/suitecrm/modules/MailMerge/get_doc.php', 'auth' => true),
    'getImage' => array('file' => '/opt/bitnami/suitecrm/include/SugarTheme/getImage.php', 'auth' => false),
    'GenerateQuickComposeFrame' => array('file' => '/opt/bitnami/suitecrm/modules/Emails/GenerateQuickComposeFrame.php', 'auth' => true),
    'DetailUserRole' => array('file' => '/opt/bitnami/suitecrm/modules/ACLRoles/DetailUserRole.php', 'auth' => true),
    'getYUIComboFile' => array('file' => '/opt/bitnami/suitecrm/include/javascript/getYUIComboFile.php', 'auth' => false),
    'UploadFileCheck' => array('file' => '/opt/bitnami/suitecrm/modules/Configurator/UploadFileCheck.php', 'auth' => true),
	'SAML'=>  array('file' => '/opt/bitnami/suitecrm/modules/Users/authentication/SAMLAuthenticate/index.php', 'auth' => false),
    'jslang'=> array('file' => '/opt/bitnami/suitecrm/include/language/getJSLanguage.php', 'auth' => true),
	'deleteAttachment' => array('file' => '/opt/bitnami/suitecrm/include/SugarFields/Fields/Image/deleteAttachment.php', 'auth' => false),
	'responseEntryPoint' => array('file' => '/opt/bitnami/suitecrm/modules/FP_events/responseEntryPoint.php', 'auth' => false),
	'formLetter' => array('file' => '/opt/bitnami/suitecrm/modules/AOS_PDF_Templates/formLetterPdf.php', 'auth' => true),
	'generatePdf' => array('file' => '/opt/bitnami/suitecrm/modules/AOS_PDF_Templates/generatePdf.php', 'auth' => true),
	'Reschedule' => array('file' => '/opt/bitnami/suitecrm/modules/Calls_Reschedule/Reschedule_popup.php', 'auth' => true),
	'Reschedule2' => array('file' => '/opt/bitnami/suitecrm/modules/Calls/Reschedule.php', 'auth' => true),
	'social' => array('file' => '/opt/bitnami/suitecrm/include/social/get_data.php', 'auth' => true),
	'social_reader' => array('file' => '/opt/bitnami/suitecrm/include/social/get_feed_data.php', 'auth' => true),
	'add_dash_page' => array('file' => '/opt/bitnami/suitecrm/modules/Home/AddDashboardPages.php', 'auth' => true),
	'retrieve_dash_page' => array('file' => '/opt/bitnami/suitecrm/include/MySugar/retrieve_dash_page.php', 'auth' => true),
	'remove_dash_page' => array('file' => '/opt/bitnami/suitecrm/modules/Home/RemoveDashboardPages.php', 'auth' => true),
	'rename_dash_page' => array('file' => '/opt/bitnami/suitecrm/modules/Home/RenameDashboardPages.php', 'auth' => true),
	'emailTemplateData' => array('file' => '/opt/bitnami/suitecrm/modules/EmailTemplates/EmailTemplateData.php', 'auth' => true),
	'emailMarketingData' => array('file' => '/opt/bitnami/suitecrm/modules/EmailMarketing/Save.php', 'auth' => true),
	'campaignTrackerSave' => array('file' => '/opt/bitnami/suitecrm/modules/CampaignTrackers/Save.php', 'auth' => true),
	'emailMarketingList' => array('file' => '/opt/bitnami/suitecrm/modules/EmailMarketing/List.php', 'auth' => true),
	'setCampaignMarketingAndTemplate' => array('file' => '/opt/bitnami/suitecrm/modules/Campaigns/WizardCampaignSave.php', 'auth' => true),
	'survey' => array('file' => '/opt/bitnami/suitecrm/modules/Surveys/Entry/Survey.php', 'auth' => false),
	'surveySubmit' => array('file' => '/opt/bitnami/suitecrm/modules/Surveys/Entry/SurveySubmit.php', 'auth' => false),
	'surveyThanks' => array('file' => '/opt/bitnami/suitecrm/modules/Surveys/Entry/Thanks.php', 'auth' => false),
    'sendConfirmOptInEmail' => array('file' => '/opt/bitnami/suitecrm/include/entryPointConfirmOptInConnector.php', 'auth' => true),
);
```

That should fix the problem.

**Comment by juanluisbaptiste** [comment]
@juan131 it works, but this shows there's another (more serious IMO) issue: this image isn't really upgradable If you need to manually fix stuff that isn't related to your configuration changes when the image breaks. Fixes should me applied automatically when a new image is delivered. This was not an issue with suitecrm but with the bitnami image it self.

Looking at the contents of that file, it isn't a config file that contains user configurations, so why it is being copied to the same volume directory ? volumes should be used to store user configuration only, and application files should be in the image only. If this file were in another place so it doesn't get persisted then this issue would have been resolved upon pulling the new image as it should be.

**Comment by juan131** [comment]
Hi @juanluisbaptiste 

I strongly agree with you. It's necessary to study every single file/directory which is being persisted and check why it was added to the "persisted files list". We need to revisit if the reason why they were added makes sense and ensure we're not persisting anything else apart from data, configuration and custom themes/modules.

I will open a task to investigate it more deeply. Thanks for you feedback.

**Comment by juanluisbaptiste** [comment]
@juan131 thanks Juan :-)

**Comment by marcosbc** [comment]
Hi @juanluisbaptiste, we have an update on the progress of this case.

Due to having found issues with both plugins and native SuiteCRM components because of not persisting all data, we will proceed with persisting the **entire** `htdocs` directory.

This means the only way to upgrade is to follow the process manually, via the app's upgrade wizard, but we will update the README. Upgrades done by pulling the new container will obviously not work for this reason.

We are already working on releasing this, and it should be available soon.

**Comment by marcosbc** [comment]
Hi @juanluisbaptiste, we released the following SuiteCRM container releases, which implements the changes we mentioned in previous comments:

- **7.10.10-debian-9-r19**
- **7.10.10-ol-7-r26**

We also updated the [README](https://github.com/bitnami/bitnami-docker-suitecrm/#upgrade-this-application) to reflect these changes.

I'm going to describe below how to migrate previous releases of the container to the newest release. Please let us know if you find any issues.

____

In order to **migrate** from previous releases (7.10.10-debian-9-r19, 7.10.10-ol-7-r23 or prior releases) please follow these steps:

- Create backups in case something goes wrong:

  * SuiteCRM container: Backup all persist data located at `/bitnami/suitecrm`.
  * MariaDB database: [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of SuiteCRM's database.

- Start a new SuiteCRM container. You might need to specify a different port configuration in order to have both the current (with the new changes) and previous container release (without them) running. Ensure docker-compose is creating a different container, with different volumes.

- Migrate SuiteCRM `htdocs` directory:

  * Inside the original SuiteCRM container, compress the entire SuiteCRM folder, following any symlink and creating the ".initialized" (so it has the same format as newer releases of the container):

        cd /opt/bitnami/suitecrm
        tar czfh /tmp/suitecrm-htdocs.tar.gz .

  * Copy the compressed tarball to the outside of the container (supposing below its id is 0123456789ab):

        docker cp 0123456789ab:/tmp/suitecrm-htdocs.tar.gz .

  * Copy that tarball to the new SuiteCRM container, which includes the new changes (supposing below its id is abcdef012345): 

        docker cp suitecrm-htdocs.tar.gz abcdef012345:/tmp

  * Inside the new SuiteCRM container, with the new changes, replace `/bitnami/suitecrm` with the contents of the tarball:

        rm -rf /bitnami/suitecrm/*
        tar xzf /tmp/suitecrm-htdocs.tar.gz -C /bitnami/suitecrm

- Restore the MariaDB database:

  * [Create a backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/) of the old MariaDB database container (supposing below its id is 54321abcdef):

        docker exec 012345abcdef mysqldump -u root bitnami_suitecrm > suitecrm-db.sql

  * Copy the backup to the new MariaDB container (supposing its id is fedcba012345):

        docker cp suitecrm-db.sql fedcba012345:/tmp

* [Restore the backup](https://docs.bitnami.com/bch/apps/redmine/administration/backup-restore-mysql-mariadb/), inside the new MariaDB database container:

        mysql -u root bitnami_suitecrm < /tmp/suitecrm-db.sql

* Stop the old SuiteCRM and MariaDB container (using the old `docker-compose.yml` file).
* Restart the new SuiteCRM and MariaDB container (using the new `docker-compose.yml` file).

**Comment by juanluisbaptiste** [comment]
@marcosbc , sorry for the late reply, got busy with other things and totally forgot to test this. 

> and creating the ".initialized" (so it has the same format as newer releases of the container):

What do mean by that ?

**Comment by juanluisbaptiste** [comment]
@marcosbc the current suitecrm install had a .initialized file so I suppose this what you meant. 

I went ahead and followed your instructions but after restarting and going to the _About_ page I see the old suitecrm version. I pulled latest image (didn't have a local copy) started the container and the About page was showing 7.11.3, after following your instructions it says 7.10.7

**Comment by marcosbc** [comment]
Hi @juanluisbaptiste, that is expected as explained in the [Notable changes section](https://github.com/bitnami/bitnami-docker-suitecrm#notable-changes):

> Due to several broken SuiteCRM features and plugins, the entire htdocs directory is now being persisted (instead of a select number of files and directories). Because of this, upgrades will not work and a full migration needs to be performed. Upgrade instructions have been updated to reflect these changes.

That means that, if you want to upgrade the SuiteCRM application, upgrading the container version will not work. Instead, you need to use the **upgrade wizard** as mentioned in the [Upgrade section](https://github.com/bitnami/bitnami-docker-suitecrm#upgrade-this-application).

**Comment by juanluisbaptiste** [comment]
@marcosbc thanks for the clarification, so what was the purpose of the upgrade instructions you posted before ?

**Comment by juanluisbaptiste** [comment]
> That means that, if you want to upgrade the SuiteCRM application, upgrading the container version will not work. Instead, you need to use the upgrade wizard as mentioned in the Upgrade section.

This is just for this case or for every upgrade from now onwards ?

**Comment by marcosbc** [comment]
Yes @juanluisbaptiste, that means it is not enough to update only the container version, you need to upgrade the SuiteCRM application manually.

If you only want to change the PHP runtime or Apache service, then you must instead change the container version.
